spring:
  application:
    name: wanted-pre-onboarding-backend
  config:
    activate:
      on-profile: local
  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WantedWork?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  paths-to-match:
#    - /jobdescriptions/**
server:
  port: 8080

---
spring:
  application:
    name: wanted-pre-onboarding-backend
  config:
    activate:
      on-profile: test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testDB;DATABASE_TO_UPPER=false
    username: sa
    password:
  sql:
    init:
      data-locations: classpath:data-test.sql
      mode: always
      platform: h2
server:
  port: 3000
