spring:
  application:
    name: wanted-pre-onboarding-backend
#  config:
#    activate:
#      on-profile: test
  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WantedWork?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password:
server:
  port: 8080
---
spring:
  application:
    name: wanted-pre-onboarding-backend
  config:
    activate:
      on-profile: development
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WantedWork?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password:
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
server:
  port: 3000
